### ISSUE TITLE
メインプロセスからレンダラープロセスへの通信を実現する

### ISSUE THREAD

**Issue by mesh1neko** [Noah0x0/noah#18]
trayアイコンのクリックとかはメインプロセスがイベントを拾うので、
現状だと、降水量を取得してもレンダラープロセスのwindowには反映できません。

処理結果をレンダラープロセスに反映できるように
メインプロセス→レンダラープロセスの通信を実現したい

**Comment by mafuyuk** [comment]
https://github.com/electron/electron/blob/master/docs/api/ipc-main.md
https://github.com/electron/electron/blob/master/docs/api/ipc-renderer.md
http://blog.techium.jp/entry/2016/03/21/083000

**Comment by runble1** [comment]
川の水位を取り溜めるように修正する。
降水量は取り溜めるよう、ファイル名に日時を入れているが、水位のデータは上書きしちゃってるので、過去データを残しておく。

**Comment by mafuyuk** [comment]
https://xwartz.gitbooks.io/electron-gitbook/content/en/api/web-contents.html

**Comment by mesh1neko** [comment]
#29

**Comment by mesh1neko** [comment]
#29 完了につきクローズ
