### ISSUE TITLE
UIからアプリを閉じることが出来るように、Quit機能を作成する。

### ISSUE THREAD

**Issue by Ihara-kenta** [Noah0x0/noah#21]
UIからアプリをシャットダウン出来ないので、Quit機能を作成する。

**Comment by Ihara-kenta** [comment]
この辺りが使えそう
https://github.com/electron/electron/blob/master/docs/api/browser-window.md#parent-and-child-windows

**Comment by mesh1neko** [comment]
#33 にて対応済みのためこちらはクローズ
