### ISSUE TITLE
表示する河川を選べるようにする

### ISSUE THREAD

**Issue by Ihara-kenta** [Noah0x0/noah#22]
selectボックスを使って(or もっといい方法があれば提案を)、様々な川に対応出来るようにする。

**Comment by Ihara-kenta** [comment]
とりあえず、国内2ヶ所、国外1ヵ所を表示出来るようにする。
下記、川が候補
- 石川: 浅野川(決定)
- 東京: 隅田川
- 台湾: どこか

**Comment by usagi-f** [comment]
フロント側の表示とデータの受け口は作成完了
