### ISSUE TITLE
think logotype

### ISSUE THREAD

**Issue by usagi-f** [Noah0x0/noah#41]
# product keywords

- water / rain / river
- safety
- calmly
- notify

![image](https://user-images.githubusercontent.com/9045135/29242069-008b5432-7fc1-11e7-8482-af8f9a145b94.png)
#37A7DB

**Comment by usagi-f** [comment]
![image](https://user-images.githubusercontent.com/9045135/29241984-724002be-7fbf-11e7-9af0-991c55e11c80.png)
http://www.1001fonts.com/arista-pro-font.html

**Comment by usagi-f** [comment]
![image](https://user-images.githubusercontent.com/9045135/29241994-96bb6eda-7fbf-11e7-9182-de4e81d0ac8c.png)
http://www.1001fonts.com/goeslim-font.html

**Comment by usagi-f** [comment]
![image](https://user-images.githubusercontent.com/9045135/29241999-b60be472-7fbf-11e7-8811-7630edfd2d3d.png)
http://www.1001fonts.com/urban-tribe-font.html

**Comment by usagi-f** [comment]
![image](https://user-images.githubusercontent.com/9045135/29242007-e45723f0-7fbf-11e7-903c-ec90d79bfc0a.png)
http://www.1001fonts.com/earth-2073-font.html

**Comment by usagi-f** [comment]
![image](https://user-images.githubusercontent.com/9045135/29242011-fd9aa9ea-7fbf-11e7-97bd-a853605a417b.png)
http://www.1001fonts.com/opificio-font.html

**Comment by usagi-f** [comment]
![image](https://user-images.githubusercontent.com/9045135/29242033-857f7304-7fc0-11e7-982b-6fa963b40f34.png)
http://www.1001fonts.com/limelight-font.html

**Comment by usagi-f** [comment]
![noah_logotype](https://user-images.githubusercontent.com/9045135/29261602-5a3c842e-810b-11e7-9e8f-15073d5dfdd9.png)

**Comment by usagi-f** [comment]
水滴の内側は波打ってるとかわいいかも…？

あまり波が立ってる画があると危険なイメージを植え付けかねないからどうだろう。。

**Comment by mafuyuk** [comment]
デザインの高山さんとどうするか方向性を合わせたほうが良いかも(波の動きのとこ

**Comment by usagi-f** [comment]
ロゴ苦手なので細部を詰めるのは任せたいｗ

**Comment by anpanmaru** [comment]
A案
![2017-08-16 22 41 16](https://user-images.githubusercontent.com/30074629/29366315-b221cb66-82d4-11e7-9075-1bb1cb65796f.png)
B案
![2017-08-16 22 41 48](https://user-images.githubusercontent.com/30074629/29366341-be504c28-82d4-11e7-95fd-309dd95f5a3d.png)
C-1案
![2017-08-16 22 41 21](https://user-images.githubusercontent.com/30074629/29366355-c5d7a48c-82d4-11e7-853a-64d87bbbb4ab.png)
C-2案 
![2017-08-16 22 41 27](https://user-images.githubusercontent.com/30074629/29366372-d08eec78-82d4-11e7-8f76-917c124d5dcb.png)
D-1案
![2017-08-16 22 41 37](https://user-images.githubusercontent.com/30074629/29366382-d9b38ebc-82d4-11e7-9780-4cc7ed62c036.png)
D-2案
![2017-08-16 22 41 42](https://user-images.githubusercontent.com/30074629/29366389-df624dbc-82d4-11e7-960c-f96e567cddae.png)

**Comment by anpanmaru** [comment]
A
水面、水位をイメージさせるビジュアル
B
ノアから船を連想してビジュアル化、結構オリジナリティがあるかも
C
水滴と水位を連想させるビジュアル
D
既存のロゴからブラッシュアップ

オーダーであったようにスタイリッシュかつシンプルなロゴを心がけました。
フォントはばっしーさんが用意してくれたもので人気が高いものをベースに1から起こしました。

※ざーーっくりと作ってあるのでいろいろ甘いです。決まってからさらに詰めたい。

------------

見せ方をいろいろ作ってはみたものの、
資料にあるデザインがベースのD-1案がしっくりくるかもしれません。
ロゴは自分達の理念をしっかり反映した形がいいと思うので
アイディアを出し合って考えた最初の形状を活かすことをお勧めしますー。

この案のこれがいいとか、これをくっつけてとかいろいろ聞きますのでコメントください！

**Comment by mesh1neko** [comment]
IMO
Google図形描画のイラストからここまで進化するなんて...

個人的な推しはD-1, C-1, B
船案結構好き。ただ一見で機能がわかりづらい気もするかなーと思ったりも。
機能面がわかりやすく出てるのはC-1案。ちょっとPOPよりな感じ？
スタイリッシュが前面に出てるのはD-1感

**Comment by runble1** [comment]
C-1、D-1が好きです！

**Comment by usagi-f** [comment]
[imo]
第一印象が良かったのはC-1案。クォリティが高そうです。

Githubで公開されてるアプリケーションっぽいな～、って思ったのはB案。
結構名前からくるイメージのシルエットが使われてるものってよくあるので。

[nits]
D-1案は個人的にはもうちょい丸みがある方が好きかなあ。。水滴の先っちょがびみょ～～～にシュッって尖ってるのが気になるｗ

**Comment by mesh1neko** [comment]
>水滴の先っちょがびみょ～～～にシュッって尖ってるのが気になるｗ

言われてみると気になってきたw

**Comment by Ihara-kenta** [comment]
個人的にはC-1案が今までのイメージから大きく外れていないという点で好みです。
次点では、B案。noahの名前から連想しやすいのでイメージが定着しやすそう。

@usagi-f さんと同じこと書いてるな。。。

**Comment by mafuyuk** [comment]
BとC-1がかっこいいいいいいいいいいいいいいいい

**Comment by usagi-f** [comment]
C-1案を採用
